# devbox.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: persona-devbox-gpu2
  labels:
    kueue.x-k8s.io/queue-name: farai
spec:
  suspend: true
  template:
    spec:
      priorityClassName: interactive
      terminationGracePeriodSeconds: 120
      containers:
      - name: devbox-container
        lifecycle:
          # This `preStop` hook, together with a relatively large `terminationGracePeriodSeconds`, lets us
          # save the data in the fast filesystem `/workspace/local-persistent` after we're done with the devbox
          # (unless there is too much of it and compressing+copying does not finish in 120s)
          preStop:
            exec:
              command:
              - bash
              - -c
              - |
                OUT_DIR="/home/dev/persistent-storage/snapshots/$(date '+%Y-%m-%d')/"
                mkdir -p "${{OUT_DIR}}"
                # backup all python files in /workspace and the /workspace/local-persistent directory
                find . -name "*.py" -o -path "./local-persistent/*" | XZ_OPT="-T14" tar -cJf "${{OUT_DIR}}/$(hostname).tar.xz" -T -
        image: ghcr.io/alignmentresearch/persona_vectors:latest
        command: ["/bin/bash", "-c"]
        args: ["sleep infinity"]
        resources:
          # Request CPUs, Limit Memory and GPUs.
          requests:
            # Since we are not setting a limit on CPU usage, CPU can burst
            # upwards as needed.
            cpu: "4"
          limits:
            memory: "100G"
            nvidia.com/gpu: "1"
            # If your devbox does not need a GPU, you should set the GPU limit to 0 instead.
            # If your devbox doesn't need an entire H100, you can use a slice of an H100 with a
            # 'MIG' GPU by uncommenting the following line and setting `nvidia.com/gpu: 0` above
            #nvidia.com/mig-1g.10gb: 1
            # Notes: it doesn't work to use multiple MIGs; The cluster may not be set up with MIG GPUs,
            # depending on our present requirements.

        env:
        - name: OMP_NUM_THREADS
          # Set this to the number of requested CPUs. Parallelism for CPU Pytorch and Numpy
          value: "4"
        - name: HF_HOME
          # Download huge LLMs only once
          value: "/home/dev/persistent-storage/hf_home"
        - name: PIP_CACHE_DIR
          # Download Python packages only once
          value: "/home/dev/persistent-storage/pip_cache"
        - name: MPLCONFIGDIR
          value: "/home/dev/persistent-storage/.cache/matplotlib"
        volumeMounts:  # specified at Container level
        - name: working-storage
          # Change `mountPath` to mount your persistent volume at a different path. Any path is possible, but we don't
          # recommend /home/dev (your home directory).
          #
          # The reason we don't recommend /home/dev is that various applications expect /home/dev to be fast: e.g. Pip
          #  saves packages in /home/dev/.cache, and installs them to /home/dev/.local by default. But NFS persistent
          #  storage is slow and can make these hard to use.
          #
          # *FILES OUTSIDE OF THIS PATH WILL STOP EXISTING WHEN THE DEVBOX STOPS*
          mountPath: /home/dev/persistent-storage

        # - name: local-storage
          # Persistent storage, but local to each node. Useful for caching stuff that is best downloaded only once, e.g.
          # huge LLMs.
          # mountPath: /local-storage

        # Mount ephemeral volume for large-disk operations
        # - name: scratch-ephemeral
          # mountPath: /scratch
        - name: scratch-saved
          mountPath: /workspace/local-persistent

        - name: dshm
          mountPath: /dev/shm
      volumes:  # specified at Pod level
      - name: working-storage
        persistentVolumeClaim:
          claimName: mkowal
      # - name: local-storage
      #   persistentVolumeClaim:
      #     claimName: local-mkowal
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: 10Gi
      # Provision an ephemeral volume, which will be deleted when the pod goes away
      # it has more available space than the root
      # - name: scratch-ephemeral
      #   ephemeral:
      #     volumeClaimTemplate:
      #       spec:
      #         accessModes: [ "ReadWriteOnce" ]
      #         storageClassName: "local-provisioned"
      #         resources:
      #           requests:
      #             # *** THIS AMOUNT MATTERS!!! ***
      #             storage: 100Gi
      # Another ephemeral volume, but the preStop hook above will save the contents of this one when the devbox exits.
      - name: scratch-saved
        ephemeral:
          volumeClaimTemplate:
            spec:
              accessModes: [ "ReadWriteOnce" ]
              storageClassName: "local-provisioned"
              resources:
                requests:
                  # *** THIS AMOUNT MATTERS!!! ***
                  storage: 100Gi

      imagePullSecrets:  # Needed for private images like `ghcr.io/alignmentresearch/flamingo-devbox:latest`
      - name: docker
      restartPolicy: Never  # Do not restart on failure of the main command
  backoffLimit: 0  # Do not retry if the main command errors
  podFailurePolicy: # But *do* make the Job create another Pod if it gets preempted by something else.
    rules:
    - action: Ignore
      onPodConditions:
      - type: DisruptionTarget
